services:
  my-llm-chat-ui:
    build:
      context: ../
      dockerfile: ./.devcontainer/dev.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspaces/my-llm-chat-ui:cached
    environment:
      - NODE_ENV=development
