services:
  panel-de-pon-ish:
    build:
      context: ../
      dockerfile: ./.devcontainer/dev.Dockerfile
    env_file:
      - ../.env
    volumes:
      - ..:/workspaces/panel-de-pon-ish:cached
    environment:
      - NODE_ENV=development
